// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4yxvXw6kbeoR0Hdvj1RBuviKecdKVC4',
    appId: '1:275371153262:web:5194b94f3430c130ff537f',
    messagingSenderId: '275371153262',
    projectId: 'flutter-chat-app-efc0c',
    authDomain: 'flutter-chat-app-efc0c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-efc0c.firebasestorage.app',
    measurementId: 'G-XMLT5HM7QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKnmSH4xpplSSLGmQyPodiJs5f55Ukac',
    appId: '1:275371153262:android:a32ca1bd6ec124d4ff537f',
    messagingSenderId: '275371153262',
    projectId: 'flutter-chat-app-efc0c',
    storageBucket: 'flutter-chat-app-efc0c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKrM_8ENXSWPS3_HVsh52uw2LjViT8Kdg',
    appId: '1:275371153262:ios:7469e151eabd3e51ff537f',
    messagingSenderId: '275371153262',
    projectId: 'flutter-chat-app-efc0c',
    storageBucket: 'flutter-chat-app-efc0c.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKrM_8ENXSWPS3_HVsh52uw2LjViT8Kdg',
    appId: '1:275371153262:ios:7469e151eabd3e51ff537f',
    messagingSenderId: '275371153262',
    projectId: 'flutter-chat-app-efc0c',
    storageBucket: 'flutter-chat-app-efc0c.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa4yxvXw6kbeoR0Hdvj1RBuviKecdKVC4',
    appId: '1:275371153262:web:90b59813a09de9c6ff537f',
    messagingSenderId: '275371153262',
    projectId: 'flutter-chat-app-efc0c',
    authDomain: 'flutter-chat-app-efc0c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-efc0c.firebasestorage.app',
    measurementId: 'G-3DVKZTK9YJ',
  );
}
